from abc import ABC, abstractmethod

class BaseParser(ABC):
    """Базовый контракт для подключения новых магазинов."""
    @abstractmethod
    def search(self, query: str): ...
    @abstractmethod
    def parse(self, source): ...
    @abstractmethod
    def save(self, offer): ...
    @abstractmethod
    def update(self): ...
